package atividade01;
public class ClassePrincipal {
    public static void main(String[] args) {
        Lampada L1 = new Lampada();
        L1.cor = "Branca";
        L1.marca = "Philips";
        L1.potencia = 20;
        L1.volt = 220;
        L1.Ligar();
        L1.Desligar();
        L1.Queimar();
        L1.impDados();
        Televisao T1 = new Televisao();
        T1.marca = "LG";
        T1.modelo = "LG K51";
        T1.polegadas = 42;
        T1.preço = 2790;
        T1.Ligar();
        T1.Desligar();
        T1.PassarCanal();
        T1.impDados2();
        Elevador E1 = new Elevador();
        E1.marca = "Atlas Schindler";
        E1.andares = 8;
        E1.capacidade = 12;
        E1.pesomax = 1800;
        E1.Subir();
        E1.Descer();
        E1.Parar();
        E1.impDados3();
        Cadeira C1 = new Cadeira();
        C1.cor = "Amarela";
        C1.marca = "Skol";
        C1.pesomax = 120;
        C1.preço = 60;
        C1.Abrir();
        C1.Fechar();
        C1.Desmontar();
        C1.impDados4();
        Aluno A1 = new Aluno();
        A1.nome = "Vinicio Duca Bandeira";
        A1.idade = 15;
        A1.rg = "0000000000-0";
        A1.cpf = "000.000.000-00";
        A1.Estudar();
        A1.FazerAtvs();
        A1.IrCasa();
        A1.impDados5();
        Datashow D1 = new Datashow();
        D1.marca = "Epson";
        D1.preço = 4000;
        D1.resoluçao = "1080p";
        D1.entrada = "USB";
        D1.Ligar();
        D1.Desligar();
        D1.Trasmitir();
        D1.impDados6();
        Microondas M1 = new Microondas();
        M1.cor = "Branco";
        M1.marca = "Brastemp";
        M1.preço = 1500;
        M1.volt = 220;
        M1.Ligar();
        M1.Desligar();
        M1.Esquentar();
        M1.impDados7();
    }
    }
